name: Test and deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: |
        yarn install
        yarn test
      env:
        CI: true
    - if: github.ref == "refs/heads/master"
      run: |
        yarn build
        yarn gh-pages -e "https://$GITHUB_TOKEN@github.com/motemen/kanji-slider.git" -d dist
