name: Test and deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: |
        yarn install
        yarn lint --no-fix --max-warnings=0
        yarn test
      env:
        CI: true
    - if: github.ref == 'refs/heads/master'
      name: deploy
      run: |
        git config --global user.email "motemen@gmail.com"
        git config --global user.name  "GitHub Actions"
        git remote set-url origin "https://motemen:${{ secrets.GITHUB_TOKEN }}@github.com/motemen/kanji-slider.git"
        yarn build
        yarn gh-pages -d dist
